"""track material processing progress

Revision ID: 015baa44a711
Revises: 20260502_chunks
Create Date: 2026-05-02 14:46:49.600639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015baa44a711'
down_revision: Union[str, Sequence[str], None] = '20260502_chunks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('course_materials', sa.Column('total_chunks', sa.Integer(), nullable=True))
    op.add_column('course_materials', sa.Column('processed_chunks', sa.Integer(), nullable=True))
    
    # Fill existing rows
    op.execute("UPDATE course_materials SET total_chunks = 0, processed_chunks = 0")
    
    # Make non-nullable
    op.alter_column('course_materials', 'total_chunks', nullable=False)
    op.alter_column('course_materials', 'processed_chunks', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course_materials', 'processed_chunks')
    op.drop_column('course_materials', 'total_chunks')
    # ### end Alembic commands ###
