"""empty message

Revision ID: 1a68ae6f82ce
Revises: ca535974d892
Create Date: 2026-05-01 14:13:08.935509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a68ae6f82ce'
down_revision: Union[str, Sequence[str], None] = 'ca535974d892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('courses', 'materials_content')
    op.alter_column('user_skills', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'career_goal',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('users', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('users', 'default_skill_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'default_learning_style',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'default_study_time',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'default_study_time',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'default_learning_style',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'default_skill_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'interests',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('users', 'career_goal',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_skills', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('courses', sa.Column('materials_content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('course_materials')
    # ### end Alembic commands ###
