"""fix_course_id_autoincrement

Revision ID: 67c94e0d0429
Revises: 1a68ae6f82ce
Create Date: 2026-05-01 14:26:00.580458

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67c94e0d0429'
down_revision: Union[str, Sequence[str], None] = '1a68ae6f82ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Manual SQL to add identity/autoincrement to existing column
    op.execute('ALTER TABLE courses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY')
    # Sync sequence
    op.execute("SELECT setval(pg_get_serial_sequence('courses', 'id'), COALESCE(max(id), 0) + 1, false) FROM courses")


def downgrade() -> None:
    op.execute('ALTER TABLE courses ALTER COLUMN id DROP IDENTITY IF EXISTS')
