"""add_plan_id_to_course_materials

Revision ID: aa25908536e6
Revises: dec6f1a221f8
Create Date: 2026-05-04 09:03:23.904635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa25908536e6'
down_revision: Union[str, Sequence[str], None] = 'dec6f1a221f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course_materials', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'course_materials', 'learning_plans', ['plan_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'course_materials', type_='foreignkey')
    op.drop_column('course_materials', 'plan_id')
    # ### end Alembic commands ###
